### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by lalauya1122** [zelebez6969/BOT-EATER#1]
Unable to execute

He can't work

**Comment by NUNUSPX** [comment]
how do you execute it?

**Comment by lalauya1122** [comment]
PYTHON2

**Comment by NUNUSPX** [comment]
this py3

**Comment by lalauya1122** [comment]
Python 3 is also unable to execute him

**Comment by lalauya1122** [comment]
python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 2, in <module>
    from linepy import *
  File "/storage/emulated/0/Download/hello/保護2/linepy/__init__.py", line 1, in <module>
    from .client import LINE
  File "/storage/emulated/0/Download/hello/保護2/linepy/client.py", line 2, in <module>
    from akad.ttypes import Message
  File "/storage/emulated/0/Download/hello/保護2/akad/ttypes.py", line 11, in <module>
    from thrift.TRecursive import fix_spec
ModuleNotFoundError: No module named 'thrift.TRecursive'

**Comment by NUNUSPX** [comment]
pip install thrift

**Comment by lalauya1122** [comment]
I installed but he still can't perform

**Comment by lalauya1122** [comment]
What needs to be installed

**Comment by TeamYok** [comment]
i m also done thrift.TRecursive.py after doing this not work auto close it . same error

**Comment by hatcherfang** [comment]
How to solve the case?
